//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRelationship
    {
        public string UserId { get; set; }
        public string FriendId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public int RelationshipId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
